### ISSUE TITLE
HEX logo 

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvarSIGNs#15]
- [x] take one of the IRFs using oil data and **bsvarSIGNs** package
- [x] choose two crazy colours @adamwang15

**Comment by donotdespair** [comment]
Hey @adamwang15 

How are you? Have a look at [that!](https://github.com/donotdespair/naklejki/blob/master/bsvarSIGNs/bsvarSIGNs.png)

That's just a first version! Colours, IRFs, composition - they all can change. But this is roughly speaking what I was thinking of. The script there includes the whole reproducible workflow that should produce identical output on your side. It estimates the model according to the example from our package, produces the figures and the logo. For the moment, I only included in the figure the 250 orthogonal IRFs. There is code that would include the IRF that is the closest to the median of those plotted. But this addition does not look good. We can either try making it look good or skip it.

Feel free to propose changes to the repo (on this sticker). To do that, you have to fork the repo, implement changes, commit, and submit them as a pull request.

There's not a good place in the package structure to include the script there. So, let work on it in this repo and then, include it in the package when the logo design is finished :)

Feel free to write to me if you would like to flow to look differently, of course!

Cheers, T

![bsvarSIGNs](https://github.com/bsvars/bsvarSIGNs/assets/78328370/dbbf1c10-92a9-4328-a992-6a4dd1dc6b66)

**Comment by adamwang15** [comment]
Hey @donotdespair,

I just submitted a pull request with some new colors! But seems the code cannot reproduce the exact IRF figure you have, they are cut at the top, otherwise I think it's pretty cool!

**Comment by donotdespair** [comment]
Hey @adamwang15 

That's cool! May I ask you to describe what colours did you chose? I am asking as in the submission I could see blue and pink, but when I merged, it's green and beige. So, which one? Currently, on my side it's:

![bsvarSIGNs](https://github.com/bsvars/bsvarSIGNs/assets/78328370/17c422cd-1f66-4966-9be0-16608ef2d5b6)

**Comment by adamwang15** [comment]
It's blue and pink. Huh strange, green and beige is one of the previous attempts.

**Comment by donotdespair** [comment]
OK @adamwang15 

blue and pink are a bit more *crazy* (as I asked) than calm green and boring beige :) Could you update this?

And also, please, make certain the colors have 6-sign code, and not 8:
```
bsora  = "#2BAE66FF"
bsblu  = "#FCF6F5FF"
```
I should have provided the feedback in your PR. I'll revise the code there this time :)

We still have to work on the IRFs' shape. This one is a bit boring with too many lines being nearly horizontal. We'll come back to this, when we will be working on the reproduction of the results.

Thanks!

Cheers, T

**Comment by donotdespair** [comment]
I think that this impulse response would look fun in the logo. What do you say @adamwang15 ? And I think I saw you reproducing it quite closely, right?

![Image](https://github.com/bsvars/bsvarSIGNs/assets/78328370/bf8f5f7d-36bf-4b0a-85ab-a748d5c57df2)

**Comment by adamwang15** [comment]
@donotdespair Hahaha, Indeed this is one chubby irf! We can definitely use it as the logo.

And yes, it can be reproduced with example code in the readme file.

**Comment by donotdespair** [comment]
Hey @adamwang15 So now, we need to put it into `naklejki` repo and do it! Also no rush :) I was just sharing ideas 💯
