### ISSUE TITLE
Implement Normal-Inverse-Wishart sampler

### ISSUE THREAD

**Issue by adamwang15** [bsvars/bsvarSIGNs#18]
- [x] sample sigma from inverse Wishart
- [x] sample A given sigma from normal
- [x] DONE: check the IW sampler
- [x] NOPE: correct the **cpp** implementation of the algo from `10 mxcs.pdf` slide 13 @donotdespair 
- [x] NOPE: implement the algo from BRL1999 (it's different) @donotdespair 

future considerations:

- [x] NOPE WE'RE NOT DOING THIS test other ways for sampling sigma, e.g. equation-by-equation with chol(sigma)
- [ ] sample hyperparameters as in [Giannone, Domenico, Michele Lenza, and Giorgio E. Primiceri (2015)](https://direct.mit.edu/rest/article/97/2/436/58236/Prior-Selection-for-Vector-Autoregressions)
- [ ] parallelize with OpenMP

**Comment by donotdespair** [comment]
Thanks @adamwang15 !

**Comment by donotdespair** [comment]
Nothing works!
