### ISSUE TITLE
Just do it!

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvarSIGNs#2]
- [x] Think of how to modify `specify_bsvarSIGN` to accommodate sign restrictions on contemporaneous effects `B` and impulse responses at 0 horizon #4 
- [x] Think of how to modify cpp function `bsvar_sign_cpp` for sign restrictions
- [x] add ADRR data
- [x] add help file for this data (hint: check out **bsvars** package)

**Comment by adamwang15** [comment]
bb1d102

**Comment by donotdespair** [comment]
All done here!
