### ISSUE TITLE
notation change

### ISSUE THREAD

**Issue by adamwang15** [bsvars/bsvarSIGNs#20]
Change notation from A (autoregressive matrix) and B (structural matrix) to (B, Sigma, Q) and (A0, Aplus) as in RRWZ (2010).

We're working with matrices `B` (`KxN`), `Sigma` (`NxN`), `Q` (`NxN`), and `Theta0 = chol(Sigma, "lower") * Q` (`NxN`)

- [ ] cpp code in ``sample_Q``
- [ ] returned posterior parameters
- [x] revise **cpp** function for `ir1_cpp`
- [x] a new **cpp** function `bsvarSIGNs_ir`
- [x] revise **cpp** function for `hd1_cpp`
- [ ] a new **cpp** function for `fevd`
- [ ] a new **cpp** function for `forecast`

## In help files and documentation

We need to use the following model notation (otherwise people will hate us!)
```
y_t = A_1 y_{t-1} + e_t  
e_t = Theta_0 u_t

Y = XB + E  
E = U Theta_0'
```

**Comment by donotdespair** [comment]
Hey @adamwang15  let's come back to the conversation. Basically, I would really like the notation across packages to not vary too much. I would really like to keep the autorytecie matrix called 'A'. Other matrices can be called as we agreed. For this package, we shall not strictly advert to ARRW notation as we will also be including other people's models. What do you say?

**Comment by adamwang15** [comment]
Hey @donotdespair no problem! How about we keep using ``B`` as the autoregressive matrix in the cpp code, then return ``A = B`` as the posterior parameter?

I think we can even return ``A = B'`` (which is what happens now), so that ``A`` is ``NxK`` and coherent across packages. You could consider including ``Theta0`` in ``bsvars`` and have the same ``irf, fevd, forecast`` for all packages (maybe I can do this with a pull request if you agree).
 
So model in the help file can be (with ``N`` equal to the rows of ``Y, X, E, U``)
```
Y = AX + E  
E = Theta0 U 
```

**Comment by donotdespair** [comment]
Hey @adamwang15 thanks! Let me think for a day about coherent naming conventions across packages. There are too many inconsistent conventions in the literature...

I am pretty certain `Theta0` will stay. And Yes, I could rewrite **bsvars** functions so `irf1` takes as input RF autoregressive parameters and `Theta0`. it's a good idea! We could reuse the functions in our package then!

:)

**Comment by donotdespair** [comment]
OK @adamwang15 we decided to not proceed!
