### ISSUE TITLE
coherent bsvars notation

### ISSUE THREAD

**Issue by adamwang15** [bsvars/bsvarSIGNs#27]
Notations in **R** should be coherent with `bsvars` and notations in **C++** should be coherent with original papers.

- [x] transpose Y, X, Ysoc, Ysur, Xsoc, Xsur, V matrices
- [x] change B in prior to A
- [x] remove Vp, Vd in prior

**Comment by adamwang15** [comment]
Hey @donotdespair now all the objects have the same dimensions as in `bsvars`! Including `Y` (NxT) and `X` (KxT), so some examples are not passing the checks.

**Comment by donotdespair** [comment]
Hey @adamwang15 This is great! Thanks!

Could you prepare here a list of file that you went thorugh and implemented changes. It would greatly help to work on corrections of the rest of the package!

Cheers, T

**Comment by adamwang15** [comment]
@donotdespair Of course! I have only changed these two R files, the idea is to transpose everything just before feeding them to the cpp functions (and cpp functions are kept the same).

- estimate.BSVARSIGN.R
- specify_bsvarSIGN.R

For example, in `estimate` before calling `bsvar_sign_cpp`

```r
prior$B             = t(prior$A)
prior$Ysoc          = t(prior$Ysoc)
prior$Xsoc          = t(prior$Xsoc)
prior$Ysur          = t(prior$Ysur)
prior$Xsur          = t(prior$Xsur)
Y                   = t(data_matrices$Y)
X                   = t(data_matrices$X)
```

**Comment by donotdespair** [comment]
- [ ] update `forecast` for the transposes!
