### ISSUE TITLE
Include dependencies on bsvars

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvarSIGNs#4]
## Use **bsvars** exported code whenever possible

- [x] **cpp** files `bsvars_sign.cpp`: removed copy/pasted functions and included dependencies
- [x] included **bsvars** in `LinkingTo` in file `DESCRIPTION`
- [x] compiled
- [x] after recoding **bsvars** change the individual samplers in file `bsvar_sign.cpp` to *fill by assignment*
- [x] adjust `specify_bsvarSIGN` so that it inherits from `specify_bsvar` as much as possible
  - [x] `data_matrices`
  - [x] `specify_identification`

**Comment by donotdespair** [comment]
OK @adamwang15 

I have adjusted the **bsvars** package by removing the filling by reference and implemented the changes in our package. But, for now, I only adjusted the GH repo and did not submit the changes to CRAN. This has consequences:
1. to make our package work on our laptops, we need the newest developer's version of **bsvars** installed. So, uninstall the package. Restart RStudio. Install the package by running:
```
devtools::install_git("https://github.com/bsvars/bsvars.git")
```
Restart RStudio. Now, you can work with the development, and it should work. Can you confirm.
2. The other consequence is that the GH Actions will fail until I submit the new version of **bsvars** to CRAN. I will do this, but not this week.

I checked and after doing all this, the sampler works fine! It samples draws from the posterior! YAY!

Cheers, T

**Comment by donotdespair** [comment]
Hey @adamwang15 So, just to not waste computational resources, I disabled the GH Action to check the package. I will re-enable it, when the new version of **bsvars** lands on CRAN. Cheers, T

**Comment by adamwang15** [comment]
Great! Thanks for the instructions, I confirm it works on my laptop now as well.

> Hey @adamwang15 So, just to not waste computational resources, I disabled the GH Action to check the package. I will re-enable it, when the new version of **bsvars** lands on CRAN. Cheers, T

No problem, take your time!

**Comment by donotdespair** [comment]
DONE!
