### ISSUE TITLE
Plot

### ISSUE THREAD

**Issue by Usukhbayar13** [bsvars/bsvarSIGNs#49]
Can i plot Response of 1 shock?

**Comment by donotdespair** [comment]
Hi @Usukhbayar13 

Thanks for your question and for reacing out! Yes, of course. It's possible using our `plot_ribbon()` function. You just have to work with the objects a bit 😄 

Here's a sample code that estimates th model and impulse responses and then, picks the response of the second variable to the first shock and plots it.
```
set.seed(123)
us_fiscal_lsuw |>
  specify_bsvar$new() |>
  estimate(S = 500) |> 
  estimate(S = 10000) |> 
  compute_impulse_responses(horizon = 8) -> irfs

plot_ribbon(irfs[2,1,,], main = "impulse response")
```
And here are two IRFs in one plot:
```
plot_ribbon(irfs[2,1,,], main = "impulse response", ylim = c(-0.01,0.04))
plot_ribbon(irfs[1,1,,], add = TRUE)
```
Does this work for you?

Greetings, 

Tomasz

**Comment by Usukhbayar13** [comment]
It works. Thanks a lot 😊.

**Comment by donotdespair** [comment]
I'm glad! Cheers, T
